@API_HostAddress = http://localhost:5208


POST {{API_HostAddress}}/orders
Content-Type: application/json

{
  "orderNumber":"ORD-{{$randomInt}}",
  "productCode":"Product-1",
  "quantity":5,
  "vendorName":"Cool Stuff Inc."
}

###
