@API_HostAddress = http://localhost:5208

// @name SubmitOrder
POST {{API_HostAddress}}/orders
Content-Type: application/json

{
  "orderNumber":"ORD-{{$randomInt}}",
  "productCode":"Product-1",
  "quantity":5,
  "vendorName":"Cool Stuff Inc."
}

###

// @name GetSubmittedOrder
GET {{SubmitOrder.response.headers.Location}}

###

// @name ApproveSubmittedOrder
POST {{SubmitOrder.response.headers.Location}}/approve
Content-Type: application/json

{
    "approvedBy":"Mike Sigsworth"
}
